name: DevSecOps Workflow for MyVodafoneApp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Job is going on"
          sleep 20

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "test Job is going on"
          sleep 20

  oast-safety:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2

      - name: Installing Pip
        run: sudo apt install python3-pip

      - name: Installing safety
        run: pip install safety

      - name: run safety scan
        run: safety check -r requirements.txt -o output.json --json
          
        continue-on-error: true

      - name: Upload the Safety Output file
        uses: actions/upload-artifact@v2
        with:
          name: Safety-Output-File
          path: output.txt
        if: always()

  deployment:
    runs-on: ubuntu-latest
    needs: oast-safety
    steps:
      - run: |
          echo "deployment Job is going on"
          sleep 15
